app:
  name: CurrencyExchangeApp
  port: :3000

database:
  dsn: root:root@tcp(raspberrypi.local:3306)/test?charset=utf8mb4&parseTime=True&loc=Local
  MaxIdleConns: 11
  MaxOpenCons: 114

redis:
  addr: raspberrypi.local:6379
  DB: 0
  Password: ""