es:
    url: http://127.0.0.1:9200
    username: ""
    password: ""
    is_console_print: true
jwt:
    access_token_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    refresh_token_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    access_token_expiry_time: 2h
    refresh_token_expiry_time: 7d
    issuer: go_blog
mysql:
    host: raspberrypi.local
    port: 3306
    config: charset=utf8mb4&parseTime=True&loc=Local
    db_name: test
    username: root
    password: root
    max_idle_conns: 10
    max_open_conns: 100
    log_mode: info
redis:
    address: raspberrypi.local:6379
    password: ""
    db: 0
system:
    host: 0.0.0.0
    port: 8080
    env: release
    router_prefix: api
    use_multipoint: true
    sessions_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    oss_type: local
zap:
    level: info
    filename: log/go_blog.log
    max_size: 200
    max_backups: 30
    max_age: 5
    is_console_print: true